Repository AxonIQ/reference-guide, pull requests merged in 2019-03, with the labels that each got.

#65 Internal APIs notes about stability guarantees.
  operations-guide/setting-up-axon-server/axon-server-clustering.md
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#69 Guide adjustments in regards to new features introduces in Axon Framework 4.1
  configuring-infrastructure-components/event-processing/event-processors.md
  implementing-domain-logic/event-handling/dispatching-events.md
  implementing-domain-logic/event-handling/handling-events.md
  implementing-domain-logic/query-handling/handling-queries.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#70 Improvements
  introduction/architecture-overview/architecture-overview.md
  introduction/architecture-overview/ddd-cqrs-concepts.md
  introduction/architecture-overview/event-driven-microservices.md
Labels: Priority 3: Could, Status: Resolved, Type: Bug

#71 Fixing typos
  implementing-domain-logic/command-handling/dispatching-commands.md
  introduction/architecture-overview/architecture-overview.md
  introduction/architecture-overview/ddd-cqrs-concepts.md
  introduction/architecture-overview/event-driven-microservices.md
  operations-guide/setting-up-axon-server/axon-server-clustering.md
Labels: Priority 2: Should, Status: Resolved, Type: Bug

#72 Typos
  setting-up/maven-dependencies.md
  setting-up/spring-boot.md
Labels: Priority 2: Should, Status: Resolved, Type: Bug
