Repository AxonIQ/reference-guide, pull requests merged in 2020-01, with the labels that each got.

#107 Document how to close emitting side once we are done using subscription queries.
  implementing-domain-logic/query-handling/dispatching-queries.md
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#109 Fix typo pleased -> placed in external-command-handler.md
  implementing-domain-logic/command-handling/external-command-handler.md
Labels: Priority 4: Would, Status: Resolved, Type: Bug

#112 Add TrackingToken parameter to EventHandling docs
  implementing-domain-logic/event-handling/handling-events.md
Labels: Ideal for Contribution, Priority 4: Would, Status: In Progress, Type: Feature
