Repository AxonIQ/reference-guide, pull requests merged in 2020-07, with the labels that each got.

#147 Revamped Security Section
  SUMMARY.md
  axon-server/introduction.md
  axon-server/security/README.md
  axon-server/security/access-control.md
  axon-server/security/ssl.md
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement

#149 Typos
  axon-server/administration/admin-configuration/command-line-interface.md
  axon-server/administration/admin-configuration/rest-api.md
  axon-server/administration/monitoring/actuator-endpoints.md
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#148 Micrometer tags/dimensions documented.
  axon-framework/monitoring-and-metrics.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#153 Revamped Installation Section (Part 2 - Docker/K8s)
  README.md
  SUMMARY.md
  axon-framework/monitoring-and-metrics.md
  axon-framework/queries/README.md
  axon-server/administration/admin-configuration/configuration.md
  axon-server/administration/multi-context.md
  axon-server/installation/README.md
  axon-server/installation/docker-k8s/README.md
  axon-server/installation/docker-k8s/axon-server-ee.md
  axon-server/installation/docker-k8s/axon-server-se.md
  extensions/tracing.md
  getting-started/quick-start.md
  release-notes/rn-axon-framework/rn-af-minor-releases.md
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement
