Repository AxonIQ/reference-guide, pull requests merged in 2020-08, with the labels that each got.

#154 Global Redirect changes
  .gitbook.yaml
  axon-framework/queries/README.md
  extensions/tracing.md
Labels: Priority 1: Must, Status: Resolved, Type: Bug

#155 Axonserver 4.4 new features
  axon-server/administration/admin-configuration/command-line-interface.md
  axon-server/administration/backup-and-messaging-only-nodes.md
  axon-server/administration/clustering.md
  axon-server/administration/command-line-interface.md
  axon-server/administration/multi-context.md
  axon-server/administration/tagging.md
  release-notes/rn-axon-server/README.md
  release-notes/rn-axon-server/rn-as-major-releases.md
  release-notes/rn-axon-server/rn-as-minor-releases.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#156 Axon Framework 4.4 new features
  SUMMARY.md
  axon-framework/axon-framework-commands/README.md
  axon-framework/axon-framework-commands/command-handlers.md
  axon-framework/axon-framework-commands/configuration.md
  axon-framework/axon-framework-commands/exception-handling.md
  axon-framework/axon-framework-commands/modeling/aggregate.md
  axon-framework/axon-framework-commands/modeling/multi-entity-aggregates.md
  axon-framework/deadlines/event-schedulers.md
  axon-framework/events/event-handlers.md
  axon-framework/events/event-processors.md
  axon-framework/events/event-serialization.md
  axon-framework/messaging-concepts/exception-handling.md
  axon-framework/messaging-concepts/message-intercepting.md
  axon-framework/monitoring-and-metrics.md
  axon-framework/queries/README.md
  axon-framework/queries/configuration.md
  axon-framework/queries/exception-handling.md
  axon-framework/tuning/event-snapshots.md
  release-notes/rn-axon-framework/README.md
  release-notes/rn-axon-framework/rn-af-major-releases.md
  release-notes/rn-axon-framework/rn-af-minor-releases.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#158 Cluster Template ref guide
  .gitbook/assets/cluster-template-default-configuration.png
  .gitbook/assets/cluster-template-export-button.png
  SUMMARY.md
  axon-server/administration/admin-configuration/README.md
  axon-server/administration/admin-configuration/cluster-template.md
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#157 Reactor Gateways ref-guide
  SUMMARY.md
  extensions/reactor/introduction.md
  extensions/reactor/reactive-gateways/reactive-gateways.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#159 Semantic Changes to Cluster Template page
  SUMMARY.md
  axon-server/administration/admin-configuration/cluster-template.md
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement
