Repository AxonIQ/reference-guide, pull requests merged in 2020-02, with the labels that each got.

#114 Typo in 'messaging concepts' guide: wvent -> event
  configuring-infrastructure-components/messaging-concepts/messaging-concepts.md
Labels: Priority 3: Could, Status: Resolved, Type: Bug

#113 Added Info about global clock to docs
  configuring-infrastructure-components/deadlines.md
Labels: Priority 2: Should, Status: Resolved, Type: Enhancement

#119 Several documentation adjustments for minor features/enhancements
  configuring-infrastructure-components/deadlines.md
  configuring-infrastructure-components/event-processing/event-bus-and-event-store.md
  implementing-domain-logic/command-handling/testing.md
  operations-guide/production-considerations/monitoring-and-metrics.md
  operations-guide/production-considerations/versioning-events.md
  setting-up/spring-boot.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#108 Aggregate Polymorphism.
  SUMMARY.md
  implementing-domain-logic/command-handling/aggregate-polymorphism.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#120 4.3 Release Notes
  introduction/release-notes/bug-fixes.md
  introduction/release-notes/release-notes.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#121 Aggregate Command Handler Creation Policy
  implementing-domain-logic/command-handling/aggregate.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature
