Repository AxonIQ/reference-guide, pull requests merged in 2020-10, with the labels that each got.

#164 docs: describe correlation data provider, fix #104
  SUMMARY.md
  axon-framework/messaging-concepts/message-correlation.md
  axon-framework/messaging-concepts/message-intercepting.md
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#166 Fix Reactor extension's URL mapping
  SUMMARY.md
  extensions/reactor/reactor.md
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#167 Improved the explanation of content type converters
  axon-framework/events/event-serialization.md
Labels: Type: Enhancement

#169 fix: typo in Axon Server Flow Control description
  axon-server-introduction.md
Labels: Priority 3: Could, Status: Resolved, Type: Bug

#168 update extension tracing guide
  extensions/tracing.md
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#170 Corrrected typos in Command Handler description
  axon-framework/axon-framework-commands/command-handlers.md
Labels: Priority 4: Would, Status: Resolved, Type: Bug

#171 docs: removed unnessesary line breaks
  axon-framework/axon-framework-commands/modeling/aggregate-polymorphism.md
Labels: Priority 4: Would
