Repository AxonIQ/reference-guide, pull requests merged in 2021-12, with the labels that each got.

#233 Typo & minor adjustments in Backups section of AS docs
  axon-server/administration/backups.md
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#236 Expand upon the exception handler section
  axon-framework/messaging-concepts/message-intercepting.md
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#237 Fine-tune Distributing Events section
  axon-framework/events/event-bus-and-event-store.md
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#227 docs: described the upcaster support in extension-kafka
  extensions/kafka.md
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#238 Release notes for AS-EE 4.5.12
  release-notes/rn-axon-server/rn-as-minor-releases.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#239 Missing docker container name
  axon-server/installation/docker-k8s/axon-server-se.md
Labels: Type: Bug, Priority 3: Could, Status: In Progress, Ideal for Contribution
