Repository AxonIQ/reference-guide, pull requests merged in 2021-04, with the labels that each got.

#198 Add a section about the Bill of Materials
  axon-framework/modules.md
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement

#199 [#188] Command Bus Infrastructure adjustments
  axon-framework/axon-framework-commands/command-handlers.md
  axon-framework/axon-framework-commands/infrastructure.md
  extensions/jgroups.md
  extensions/spring-cloud.md
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement, Type: Feature

#201 Add simplified Gradle BOM import description
  axon-framework/modules.md
Labels: Ideal for Contribution, Priority 3: Could, Status: In Progress, Type: Enhancement
