Repository AxonIQ/reference-guide, pull requests merged in 2022-08, with the labels that each got.

#273 Added docs for token reset
  axon-framework/events/event-processors/streaming.md
  axon-server/administration/event-processors.md
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#251 Added description of several configuration options
  axon-server/administration/admin-configuration/configuration.md
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#278 Document how to use and access the ReplayToken.replayContext
  axon-framework/events/event-processors/streaming.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#280 Added description of command line arguments valid for all commands
  axon-server/administration/admin-configuration/command-line-interface.md
Labels: Type: Enhancement, Priority 3: Could

#279 Add Jakarta modules
  axon-framework/modules.md
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress
