Repository AxonIQ/reference-guide, pull requests merged in 2022-03, with the labels that each got.

#246 Fixed the event parameter name in the EventHandler example
  axon-framework/queries/query-dispatchers.md
Labels: Type: Bug, Priority 4: Would, Status: Resolved, Ideal for Contribution

#250 Add caveat for the context-aware upcaster
  axon-framework/events/event-versioning.md
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#231 Streaming query documentation
  axon-framework/queries/query-dispatchers.md
  axon-server/performance/flow-control.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature
