Repository AxonIQ/reference-guide, pull requests merged in 2022-11, with the labels that each got.

#293 Append `RevisionSnapshotFilter` description to Filtering Snapshot Events sub-section
  axon-framework/tuning/event-snapshots.md
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#294 Add notices on Dead-Letter Queue support for Sagas
  axon-framework/events/event-processors/README.md
Labels: Type: Enhancement, Priority 4: Would, Status: In Progress

#295 [#288] Add Token Stealing subsection to Tracking Tokens
  axon-framework/events/event-processors/streaming.md
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#296 Replace @Autowired configuration samples for ConfigurerModule
  axon-framework/events/event-processors/README.md
  axon-framework/events/event-processors/streaming.md
  axon-framework/events/event-processors/subscribing.md
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#299 Update to Mongo Extension 4.7.0
  extensions/mongo.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature
